language: r
cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true
sudo: false
warnings_are_errors: true
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'